### ISSUE TITLE
the `MemView` design around the mutability parameter could be better

### ISSUE THREAD

**Issue by nsajko** [BioJulia/MemViews.jl#1]
Currently the `MemView` type has a mutability type parameter that should be either `:mutable` or `:immutable`, something that has to be checked at run time. This results in a lack of type safety, because constructing invalid types such as `MemView{Int,3}` is possible. It also results in a lack of elegance in the definition of the constructors.

One better design would be to make the mutability type parameter a type, which can be constrained, thus providing more type safety. Furthermore, it'd make sense to add a field typed with the mutability parameter to `struct MemView`. This would make accessing the mutability parameter easier and it could make the implementation of the constructors more elegant, perhaps even the default constructors could be used. Something like this:

```julia
struct IsMutable end
struct IsNotMutable end

struct MemView{T, M<:Union{IsMutable,IsNotMutable}} <: DenseVector{T}
    ref::MemoryRef{T}
    mutability::M
    len::Int
    ...
end
```

Another possible design would be to just have separate `struct MutableMemView` and `struct ImmutableMemView` and then `MemView` could be defined as their `Union`.

**Comment by jakobnissen** [comment]
In the first iteration of this package, I did have the mutable and immutable views distinct, and has `MemView` defined as their union. I can't remember exactly why I changed it, but it was more annoying that the current design.

I agree having `:mutable` as a `Symbol` opens up for errors, such as accidentally checking if `x isa MemView{UInt8, :imutable}`. Your proposal is probably better, although I don't believe `MemView{Int, 3}` is an issue that is likely to occur in any realistic scenario. I will probably change the mutability parameter to a type instead as you suggest.

I'm not sure I understand the advantage of having the mutability as a field. Why would that ever need to be accessed as a value? Normally, people are interested in subtyping relationships like `if x isa MutableMemView`.

**Comment by nsajko** [comment]
OK, nice!

> I'm not sure I understand the advantage of having the mutability as a field. Why would that ever need to be accessed as a value? Normally, people are interested in subtyping relationships like `if x isa MutableMemView`.

Maybe it's not important here, but generally I find it's good to have the parameter types available as values (when its a singleton type, at least, making this costless), because doing `mv.mutability` is nicer than introducing an extra static parameter to the method. A hypotetical application is dispatching on the mutability, like `f(mv.mutability)`.
